// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1583993917);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1583994037);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1583991046);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1583991166);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1583994157);
user_pref("browser.cache.disk.amount_written", 912);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.search.region", "KE");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.lastModified", "Wed, 11 Mar 2020 22:04:34 GMT");
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.getAddons.cache.lastUpdate", 1583993917);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppVersion", "68.4.1");
user_pref("extensions.lastPlatformVersion", "68.4.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"wetransfer@extensions.thunderbird.net\":\"1655f922-7177-4155-83e5-3eb5381043e0\",\"default-theme@mozilla.org\":\"ed934699-8e4a-4d73-88c1-904c2930f361\",\"google@search.mozilla.org\":\"4e00761e-537c-4fce-aa2c-95942d11a1bd\",\"amazondotcom@search.mozilla.org\":\"d5d61fac-dcd7-429d-bf96-c3dabe48dad1\",\"bing@search.mozilla.org\":\"df7ddc5a-d700-458a-96c5-d0175af3fa8c\",\"ddg@search.mozilla.org\":\"609134f3-7c67-4375-a74b-79042bc0087a\",\"twitter@search.mozilla.org\":\"45149ef9-fe1b-462c-9eba-4c8c7b878a57\",\"wikipedia@search.mozilla.org\":\"027d60db-71f3-4308-87b6-4c363941aeac\"}");
user_pref("idle.lastDailyNotification", 1583994778);
user_pref("mail.ab_remote_content.migrated", 1);
user_pref("mail.append_preconfig_smtpservers.version", 2);
user_pref("mail.default_charsets.migrated", 1);
user_pref("mail.folder.views.version", 1);
user_pref("mail.openMessageBehavior.version", 1);
user_pref("mail.spam.version", 1);
user_pref("mail.ui-rdf.version", 17);
user_pref("mailnews.database.global.datastore.id", "6517e794-64bd-43a1-993a-ee4be46e38e");
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.start_page_override.mstone", "68.4.1");
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Important");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Work");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Personal");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "To Do");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Later");
user_pref("mailnews.tags.version", 2);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("places.database.lastMaintenance", 1583994778);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("security.sandbox.plugin.tempDirSuffix", "4f4a5389-c8c3-415b-a21a-cbf1b4bcbf64");
user_pref("services.blocklist.pinning.checked", 1583991369);
user_pref("services.settings.clock_skew_seconds", -203);
user_pref("services.settings.last_etag", "\"1583970742277\"");
user_pref("services.settings.last_update_seconds", 1583991369);
user_pref("services.settings.main.hijack-blocklists.last_check", 1583991369);
user_pref("services.settings.main.language-dictionaries.last_check", 1583991369);
user_pref("services.settings.main.sites-classification.last_check", 1583991369);
user_pref("services.settings.security.onecrl.checked", 1583991369);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1583994778);
user_pref("toolkit.telemetry.cachedClientID", "cd1bb854-e41a-4ab1-985c-1b2383671aea");
user_pref("toolkit.telemetry.prompted", 2);
