// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.migrationsApplied", 8);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1583936276);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 0);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 8058);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1583936247);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 89);
user_pref("browser.newtabpage.activity-stream.impressionId", "{0a3b29bd-a383-485e-ab5f-5543a56706d1}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1583936261278");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1583939861278");
user_pref("browser.search.region", "KE");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1583936252");
user_pref("browser.slowStartup.averageTime", 8271);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20200117190643");
user_pref("browser.startup.homepage_override.mstone", "72.0.2");
user_pref("browser.startup.lastColdStartupCheck", 1583936251);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1583936262560");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "72.0.2");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("dom.push.userAgentID", "e6085b43f93443e084ec70f4e2463472");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppVersion", "72.0.2");
user_pref("extensions.lastPlatformVersion", "72.0.2");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.doh-rollout@mozilla.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"2eb76723-7812-4aa6-84ed-6b84fce452c1\",\"formautofill@mozilla.org\":\"f762aae1-9519-4ad3-9c01-7af191341a83\",\"screenshots@mozilla.org\":\"17c9dce2-b2a1-45e8-a308-0ac656abdcd7\",\"webcompat-reporter@mozilla.org\":\"7d0f21c8-32d7-405b-82b3-ff6db711c885\",\"webcompat@mozilla.org\":\"7bee94fb-e613-4d25-a1e3-3a52831dac7b\",\"default-theme@mozilla.org\":\"614279a8-108e-46bb-b939-5e37fbcf4184\",\"google@search.mozilla.org\":\"3c115d12-b825-4a45-a0fd-beb964c10e09\",\"amazondotcom@search.mozilla.org\":\"400675f3-44f1-4692-875a-2bd57a85fbb3\",\"bing@search.mozilla.org\":\"e7d92956-c719-4861-8b8f-b8861998d3d3\",\"ddg@search.mozilla.org\":\"b5ac6cbf-073c-4ad0-91b7-9b2ddcb85154\",\"ebay@search.mozilla.org\":\"9b19f98e-ddde-4b5d-a44d-fa821e43440b\",\"twitter@search.mozilla.org\":\"74ef3857-b475-4237-a366-77bf2a90655f\",\"wikipedia@search.mozilla.org\":\"e99ed9ff-3b7b-4ac0-b394-f292c5c5feea\"}");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "608d26cc-e210-4015-aa74-b59c25497877");
user_pref("security.sandbox.plugin.tempDirSuffix", "10b2e906-1bbf-4ece-a094-570333727e2c");
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1583936243);
user_pref("toolkit.telemetry.cachedClientID", "623cbede-9c7d-497e-836c-9170a7a0d393");
user_pref("toolkit.telemetry.previousBuildID", "20200117190643");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
